### ISSUE TITLE
Don't use NumberOfItems32

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Metrics#30]
In https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/64 it was raised that currently NumberOfItems32 is used. This can give an incorrect average representation over time as the 'last writer wins'. This metric could be improved by using RateOfCountsPerSecond32 as that is based on averages.

**Comment by dvdstelt** [comment]
Wrong repo, @ramonsmits 
If you don't pay attention to the correct repo, how can others pay attention to a single issue inside the monitoring repo ;-)

**Comment by dvdstelt** [comment]
Moved to https://github.com/Particular/NServiceBus.Metrics.PerformanceCounters/issues/13.
