### ISSUE TITLE
Include a message mutator to add instance Id header

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/NServiceBus.Metrics#42]
If the user specifies the instance Id using the extension method, that instance Id is different from the values that ServiceControl gets.

I propose that if the user specifies the instance Id, that the same code registers a Transport Message Mutator to add the header to every outgoing message. This will mean that ServiceControl will also receive that header in the event of the message being forwarded to the error queue.

I did want to do a PR for this myself but I am not able to get the project to work at all.

**Comment by Scooletz** [comment]
Addressed by https://github.com/Particular/NServiceBus.Metrics/pull/46
