### ISSUE TITLE
Determine impact of `GetAwairer().GetResult` call in reporter

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.Metrics#5]
Not being an `async` expert I would like to make sure that there is danger of deadlocking ourselves. 

Alternatively we can use a queue so that `Report` only enqueues the reports and a separate thread started in a feature startup task pushes them to the dispatcher.

**Comment by SzymonPobiega** [comment]
pinging @danielmarbach -- is there any real danger in using `GetAwairer().GetResult()` on the `Task` returned by NServiceBus message dispatcher?

**Comment by SzymonPobiega** [comment]
After talking to Daniel it seems like the way to go is:
 * Make the whole method `private Task`
 * In the `RunReport` either use `GetAwairer`
 * Create a PR for Metrics.NET to make the reporting part `async` :-)

**Comment by SzymonPobiega** [comment]
Closed via 2c32dcaf1e948043343c8145a7b40ef1d12414fc

**Comment by mikeminutillo** [comment]
What happens if the async part throws an exception in that case?

**Comment by danielmarbach** [comment]
@mikeminutillo the reporter currently just logs an error

https://github.com/Particular/NServiceBus.Metrics/commit/2c32dcaf1e948043343c8145a7b40ef1d12414fc#diff-3c0b99203ba7e6e68ffecc9c6e2afd11R52
