### ISSUE TITLE
Discuss the API towards metric processor (wire format)

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.Metrics#7]
Issued to be discussed
 * Name of the context (currently name of the endpoint, probably need to add some unique identification such as `HostId`)
 * Adding `EnclodedMessageTypes` header:
   * Should we add it? If we add it, a normal NServiceBus endpoint would be able to process metric messages using Newtonsoft serializer
   * If so then what assembly should we use: `NServiceBus.Metrics` or original `Metrics`

**Comment by SzymonPobiega** [comment]
I think that for ease of integration we should:
 * Add `EnclodedMessageTypes` because it does not hurt us and can make consuming metrics easier
 * Use original type name in that headers so that the consuming code can be independent of `NServiceBus.Metrics` assembly

**Comment by mikeminutillo** [comment]
I was going to ask how big the current payload is. How many metrics can we get in a single message before we need to split it across multiple messages?

**Comment by mikeminutillo** [comment]
> Name of the context (currently name of the endpoint, probably need to add some unique identification such as HostId)

Is there an API from core to get a unique physical instance identifier rather than trying to build one based on Endpoint Name and Host Id?

**Comment by SzymonPobiega** [comment]
@mikeminutillo I don't think there is anything batter than `EndpointName` + `HostId`. The instance discriminator can be duplicated. 

Regarding the payload, this is a very relevant question for the Azure transports. We can have potentially quite a lot of metric values. The problem is I can't really think of a bullet-proof way of telling how many metrics I can put into a message before it gets too big for the transport. 

Should we make this user-configurable? Some safe defaults per transport?

**Comment by SzymonPobiega** [comment]
@mikeminutillo should we postpone this issue and come back to it after we have a first draft of the server-side component ready?

**Comment by mikeminutillo** [comment]
Yeah. We might be able to sort it out using filters and multiple reporters (for example). Let's build it and see what happens. As long as we split at the metric level and don't do silly stuff like breaking down into packets and trying to reassemble payload on the other side I think we'll be OK.

**Comment by SzymonPobiega** [comment]
For now I've added a test that proves we can fit 500 gauge reads in a single message: https://github.com/Particular/NServiceBus.Metrics/pull/10. Closing for now. We'll reopen if/when needed.

**Comment by SzymonPobiega** [comment]
I changed the instance identification in daa9ab0e57e63db7dbc2cc0072fd27442167ca49 to include `HostId`.
