### ISSUE TITLE
NServiceBus.Metrics.ServiceControl throws exception

### ISSUE THREAD

**Issue by progorovics** [Particular/NServiceBus.Metrics#85]
Hi, 

I've just updated to NServiceBus.Metrics.ServiceControl 3.0.1. My NSB monitoring was running fine before with 3.0.0 beta0004.

After nuget package update it throws an excpetion:

NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from transport message b95d6951-1a42-4926-9fa4-4b1555ed9737\231560 ---> System.Exception: Could not find metadata for 'Newtonsoft.Json.Linq.JObject'.
Ensure the following:
1. 'Newtonsoft.Json.Linq.JObject' is included in initial scanning. 
2. 'Newtonsoft.Json.Linq.JObject' implements either 'IMessage', 'IEvent' or 'ICommand' or alternatively, if you don't want to implement an interface, you can use 'Unobtrusive Mode'.
   bei NServiceBus.Unicast.Messages.MessageMetadataRegistry.GetMessageMetadata(Type messageType)
   bei NServiceBus.Pipeline.LogicalMessageFactory.Create(Type messageType, Object message)
   bei NServiceBus.DeserializeLogicalMessagesConnector.Extract(IncomingMessage physicalMessage)
   bei NServiceBus.DeserializeLogicalMessagesConnector.ExtractWithExceptionHandling(IncomingMessage message)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei NServiceBus.DeserializeLogicalMessagesConnector.ExtractWithExceptionHandling(IncomingMessage message)
   bei NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NServiceBus.SubscriptionReceiverBehavior.<Invoke>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NServiceBus.ReceivePerformanceDiagnosticsBehavior.<Invoke>d__2.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NServiceBus.ReceiveStrategy.<TryProcessMessage>d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NServiceBus.ReceiveOnlyNativeTransactionStrategy.<ProcessMessage>d__2.MoveNext()

**Comment by Scooletz** [comment]
Thank you @progorovics for raising it. Just to clarify: have you changed anything beside bumping up the package?

**Comment by progorovics** [comment]
No I haven't changed anything else. After rollback to version 3.0.0 beta0004 my system works fine again. I'll check my handlers now.

**Comment by tmasternak** [comment]
@progorovics can you clarify what is the source of the stacktrace? Is this from the endpoint using the new version of `NServiceBus.Metrics.ServiceControl` or the Service Control monitoring instance?

Secondly, could you please provide the version of Service Control that you are using?

**Comment by progorovics** [comment]
The source of this stacktrace is my endpoint using the new version of NServiceBus.Metrics.ServiceControl
My version of Service Control is 1.48.0. But I just recognized that there's an updated version 2.0.1. 
Should I try to upgrade now?

**Comment by tmasternak** [comment]
The upgrade to 2.0.1 of Service Control is not necessary (no changes to monitoring service have been introduced).

Could you share code for your endpoint configuration? Is there a chance that for some reason the monitoring plugin is sending data to the endpoint itself? Is there any messages that end-up i the error queue?

**Comment by progorovics** [comment]
Ok, I'd just upgraded Service Control to 2.0.1 => Monitoring runs fine
After that I'd upgraded my endpoints again to NServiceBus.Metrics.ServiceControl 3.0.1 => no exceptions, everything runs fine.
So obviously upgrading to Service Control to 2.0.1 solved this issue

**Comment by tmasternak** [comment]
@progorovics great that you were able to make it work! BTW the [troubleshooting guide](https://docs.particular.net/monitoring/metrics/queue-length-troubleshooting) might be of help if you run to any other problems while setting things up .

**Comment by fazalWahid56** [comment]
@tmasternak  Hi, i am getting the same issue with NServiceBus **7.1.6** and NServiceBus.Metrics.ServiceControl **3.0.2**.  Is there any way around?

**Comment by mikeminutillo** [comment]
Hi @fazalWahid56, I can get everything running locally with those versions. Which version of ServiceControl monitoring are you running? Mine is 2.3.0.
